### ISSUE TITLE
Routes are all missing trailing slashes

### ISSUE THREAD

**Issue by prokopsimek** [ButterCMS/vuejs-starter-buttercms#11]
Per checklist, routes all have trailing slashes, yet routes + links are all missing trailing slashes in app.

We actually need the trailing slashes due to how heroku's proxy-load balancing returns requests for static sites with iframe urls, so this was added to the checklist. Can we please have the links + routes updated to sue trailing slashes?

**Comment by gerzitom** [comment]
Resolve in #14
