### ISSUE TITLE
Warning in terminal

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/vuejs-starter-buttercms#18]
I'm getting the following warning in terminal: [`@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported`.

This may just be a [linting error](https://dev.to/imomaliev/til-2021-10-04-fix-script-setup-defineprops-is-not-defined-38ic), but either way, can it be resolved?

**Comment by gerzitom** [comment]
Solved
