### ISSUE TITLE
Autoscroll is inconsistent when navigating from another portion of site

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/vuejs-starter-buttercms#20]
[video](https://share.getcloudapp.com/eDu5Bg6q)

**Comment by ViolanteCodes** [comment]
I am also noticing this behavior when using the footer menu, e.g., from blog categories view to the index view - the "features" link appears to be the worst for this

**Comment by gerzitom** [comment]
@ViolanteCodes please, try it. I fixed it and everything is working now.
