### ISSUE TITLE
"/landing-page/" does not pass slug

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/vuejs-starter-buttercms#21]
the landing-page alternate view, `/landing-page/<slug>/`, is set up, but no matter what slug is used, the page shown is the 'landing-page-with-components' page. This means the user cannot set up a different page with page type of landing-page in butter and test it, such as the 'alternate-landing-page' currently set up in the test account.

It looks like this url routes exclusively to a HomeView, when it should likely route to something like a LandingPageView, with the '/' route passing the 'landing-page-with-components' slug.

**Comment by gerzitom** [comment]
Solves in #35
