### ISSUE TITLE
need to update demo links

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/vuejs-starter-buttercms#22]
We cannot use `http://vuejs-starter-buttercms.vercel.app/` as the demo address as this address is already claimed - can you either delete this app or assign control to us, so that we can put in the keys, etc?

**Comment by gerzitom** [comment]
@ViolanteCodes I have deleted my app, it is free for you to take over the domain. 😄

**Comment by ViolanteCodes** [comment]
> @ViolanteCodes I have deleted my app, it is free for you to take over the domain. smile

Hi @gerzitom - this has been redeployed and linked to this repo with our production key for the main app and our testing key for the development/preview branches in case you also need to test.
