### ISSUE TITLE
trailing slash missing from categories button and URL/view

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/vuejs-starter-buttercms#24]
[video](https://share.getcloudapp.com/wbuzPy5x)

**Comment by ViolanteCodes** [comment]
this is also true of search view - e.g., entering a search term and hitting the magnifying glass icon takes you to a view with out the trailing slash

**Comment by gerzitom** [comment]
@ViolanteCodes so you want the search url to look from `/blog/search?q=test` to look like this `/blog/search?q=test/`

**Comment by ViolanteCodes** [comment]
> @ViolanteCodes so you want the search url to look from `/blog/search?q=test` to look like this `/blog/search?q=test/`

yes
