### ISSUE TITLE
Final Code overview

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/vuejs-starter-buttercms#37]
Hi @orlyohreally  - can we get a final once over on this for code? @gerzitom is aware of the need to pull the unused assets, but everything else looked okay to me :)

Thanks!

**Comment by orlyohreally** [comment]
@ViolanteCodes I don't know if you've already talked about it, but why `package-lock.json` is not in the repo? It's not critical, but maybe we'd want it to be.
The only issue I've found is unused assets that is already noted and an issue is created, but I don't see that some of the images were removed https://github.com/ButterCMS/vuejs-starter-buttercms/pull/38/files

**Comment by ViolanteCodes** [comment]
@gerzitom 

Can we have the unused image assets pulled?

@orlyohreally I'll push up package-lock.json now

**Comment by gerzitom** [comment]
@ViolanteCodes @orlyohreally I have removed all unused images in #38

**Comment by orlyohreally** [comment]
@ViolanteCodes I checked the demo and it loaded for me slightly longer than before and it seems that this starter app does not have loader displayed when the content is being loaded. Compare with https://django-starter-buttercms.herokuapp.com/

**Comment by gerzitom** [comment]
@orlyohreally okey, thank you for noticing, so I will implement the loader.

**Comment by gerzitom** [comment]
@orlyohreally loaders added in #39

**Comment by ViolanteCodes** [comment]
Looks like this has been approved, going to close this issue. Nice work @gerzitom, and thank you :) we're so excited for this starter :)
