### ISSUE TITLE
Rename ENV variables to be prefixed with "VUE_" instead of "VITE_"

### ISSUE THREAD

**Issue by prokopsimek** [ButterCMS/vuejs-starter-buttercms#4]
Is there any reason to have the name prefixed with "VITE"?

**Comment by gerzitom** [comment]
Yes, there is. Ony VITE_ prefixes are exposed for the app. It is security reason from Vite engine: https://vitejs.dev/guide/env-and-mode.html.

**Comment by prokopsimek** [comment]
@ViolanteCodes Please, take a look if these var names are ok for you.

**Comment by ViolanteCodes** [comment]
> @ViolanteCodes Please, take a look if these var names are ok for you.

Yes - if it's necessary in order for the Vite engine to work, we are okay with the one-off change here. Thanks :) !
