### ISSUE TITLE
Rename the name of the project in package.json

### ISSUE THREAD

**Issue by prokopsimek** [ButterCMS/vuejs-starter-buttercms#6]
https://github.com/ButterCMS/vuejs-starter-buttercms/blob/main/package.json#L2

Should be the same as repo name - `vuejs-starter-buttercms`

**Comment by gerzitom** [comment]
Done

**Comment by prokopsimek** [comment]
@gerzitom there is still different name of the project https://github.com/ButterCMS/vuejs-starter-buttercms/blob/main/package.json#L2
