### ISSUE TITLE
Remove unused assets

### ISSUE THREAD

**Issue by prokopsimek** [ButterCMS/vuejs-starter-buttercms#7]
https://github.com/ButterCMS/vuejs-starter-buttercms/tree/main/src/assets

See e.g. Express.js changes here: https://github.com/ButterCMS/expressjs-starter-buttercms/pull/10

**Comment by prokopsimek** [comment]
What are these icons? https://github.com/ButterCMS/vuejs-starter-buttercms/tree/main/src/components/icons

**Comment by prokopsimek** [comment]
What are these icons? https://github.com/ButterCMS/vuejs-starter-buttercms/tree/main/src/components/icons

**Comment by gerzitom** [comment]
Removed

**Comment by prokopsimek** [comment]
@gerzitom Is this file necessary? https://github.com/ButterCMS/vuejs-starter-buttercms/blob/main/src/assets/base.css

**Comment by gerzitom** [comment]
No, sorry, I have removed it
